[0m18:30:13.305721 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7383ac1e67b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7383abdda2a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7383abdda270>]}


============================== 18:30:13.309212 | c0fcbdd7-2e73-4a58-8b87-4cb62868698d ==============================
[0m18:30:13.309212 [info ] [MainThread]: Running with dbt=1.8.1
[0m18:30:13.314108 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/coder/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init classicmodels_modeling', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:30:13.360335 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/home/coder/.dbt')}
[0m18:30:13.360821 [info ] [MainThread]: Creating dbt configuration folder at 
[0m18:30:13.372202 [debug] [MainThread]: Starter project path: /home/coder/miniconda/lib/python3.12/site-packages/dbt/include/starter_project
[0m18:30:13.738121 [info ] [MainThread]: 
Your new dbt project "classicmodels_modeling" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:30:13.738662 [info ] [MainThread]: Setting up your profile.
[0m18:30:57.880835 [error] [MainThread]: Encountered an error:

[0m18:30:57.884828 [error] [MainThread]: Traceback (most recent call last):
  File "/home/coder/miniconda/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/coder/miniconda/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/coder/miniconda/lib/python3.12/site-packages/dbt/cli/main.py", line 469, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/coder/miniconda/lib/python3.12/site-packages/dbt/task/init.py", line 347, in run
    self.setup_profile(profile_name)
  File "/home/coder/miniconda/lib/python3.12/site-packages/dbt/task/init.py", line 263, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/coder/miniconda/lib/python3.12/site-packages/dbt/task/init.py", line 180, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/coder/miniconda/lib/python3.12/site-packages/dbt/task/init.py", line 164, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coder/miniconda/lib/python3.12/site-packages/dbt/task/init.py", line 130, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/home/coder/miniconda/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/coder/miniconda/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:30:57.889831 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 44.690964, "process_user_time": 1.451256, "process_kernel_time": 0.194018, "process_mem_max_rss": "87320", "process_in_blocks": "37562", "process_out_blocks": "144", "command_success": false}
[0m18:30:57.901402 [debug] [MainThread]: Command `dbt init` failed at 18:30:57.901243 after 44.70 seconds
[0m18:30:57.907621 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7383abc95dc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7383abd1bc20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7383abc02420>]}
[0m18:30:57.913864 [debug] [MainThread]: Flushing usage events
